-- Cierre funcional de la demo: solicitudes de participación y auditoría.
-- Toda escritura se realiza desde Server Actions después de validar los datos
-- y, en el caso del panel, la sesión y el rol. No se exponen estas tablas al
-- cliente de Supabase.

do $$
begin
  if not exists (select 1 from pg_type where typname = 'estado_solicitud') then
    create type public.estado_solicitud as enum (
      'nueva',
      'en_revision',
      'contactada',
      'cerrada'
    );
  end if;
end
$$;

create table if not exists public.solicitudes_participacion (
  id uuid primary key default gen_random_uuid(),
  nombre text not null check (char_length(nombre) between 2 and 100),
  correo text not null check (char_length(correo) between 5 and 160),
  programa text check (programa is null or char_length(programa) <= 120),
  temas text[] not null check (cardinality(temas) between 1 and 6),
  mensaje text check (mensaje is null or char_length(mensaje) <= 1200),
  consentimiento boolean not null check (consentimiento = true),
  estado public.estado_solicitud not null default 'nueva',
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create index if not exists solicitudes_participacion_creado_en_idx
  on public.solicitudes_participacion (creado_en desc);

create index if not exists solicitudes_participacion_correo_idx
  on public.solicitudes_participacion (lower(correo), creado_en desc);

create table if not exists public.auditoria_admin (
  id bigint generated by default as identity primary key,
  usuario_id uuid references auth.users(id) on delete set null,
  usuario_email text,
  accion text not null,
  recurso_tipo text not null,
  recurso_id text not null,
  detalle jsonb not null default '{}'::jsonb,
  creado_en timestamptz not null default now()
);

create index if not exists auditoria_admin_creado_en_idx
  on public.auditoria_admin (creado_en desc);

alter table public.solicitudes_participacion enable row level security;
alter table public.auditoria_admin enable row level security;

revoke all on table public.solicitudes_participacion from anon, authenticated;
revoke all on table public.auditoria_admin from anon, authenticated;

-- El cliente privado del servidor omite RLS. No se crean políticas públicas:
-- una solicitud nunca puede listarse, modificarse ni insertarse directamente
-- desde el navegador.
